const optionalSyllabus = [
  {
    id: "sociology1",
    type: "OPTIONAL",
    paper: "PAPER_1",
    name: "Sociology Paper 1",

    topics: [
  {
    id: "sociology-the-discipline",
    name: "Sociology - The Discipline",
    subtopics: [
      {
        id: "modernity-and-social-changes",
        name: "Modernity and Social Changes in Europe and Emergence of Sociology",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "scope",
        name: "Scope of Sociology",
        estimatedMinutes: 60,
        difficulty: 1,
      },
      {
        id: "sociology-relation",
        name: "Sociology and its relation with other subjects",
        estimatedMinutes: 60,
        difficulty: 1,
      },
      {
        id: "sociology-common-sense",
        name: "Sociology And Common Sense",
        estimatedMinutes: 60,
        difficulty: 1,
      },
    ],
  },
  {
    id: "sociology-science",
    name: "Sociology as Science",
    subtopics: [
      {
        id: "science-scientific-method",
        name: "Science, scientific method and critique",
        estimatedMinutes: 80,
        difficulty: 3,
      },
      {
        id: "positivism-and-its-critique",
        name: "Major theoretical strands of Positivism and its critique",
        estimatedMinutes: 180,
        difficulty: 3,
      },
      {
        id: "fact-value-and-objectivity",
        name: "Fact value and objectivity",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "non-positivist-methodologies",
        name: "Non-positivist methodologies",
        estimatedMinutes: 150,
        difficulty: 3,
      },
    ],
  },
  {
    id: "research-methods-and-analysis",
    name: "Research Methods and Analysis",
    subtopics: [
      {
        id: "qualitative-and-quantitative-methods",
        name: "Qualitative and quantitative methods",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "techniques-of-data-collection",
        name: "Techniques of data collection",
        estimatedMinutes: 150,
        difficulty: 2,
      },
      {
        id: "variables-sampling-hypothesis",
        name: "Variables, sampling, hypothesis, reliability and validity",
        estimatedMinutes: 150,
        difficulty: 3,
      },
    ],
  },
  {
    id: "sociological-thinkers",
    name: "Sociological Thinkers",
    subtopics: [
      {
        id: "karl-marx",
        name: "Karl Marx - Historical Materialism, Mode of Production, Alienation, Class Struggle",
        estimatedMinutes: 240,
        difficulty: 3,
      },
      {
        id: "emile-durkheim",
        name: "Emile Durkheim - Division of Labour, Social Fact, Suicide, Religion and Society",
        estimatedMinutes: 240,
        difficulty: 3,
      },
      {
        id: "max-weber",
        name: "Max Weber - Social Action, Ideal Types, Authority, Bureaucracy, Protestant Ethic and Spirit of Capitalism",
        estimatedMinutes: 240,
        difficulty: 3,
      },
      {
        id: "talcott-parsons",
        name: "Talcott Parsons - Social System, Pattern Variables",
        estimatedMinutes: 180,
        difficulty: 3,
      },
      {
        id: "robert-k-merton",
        name: "Robert K. Merton - Latent and Manifest Functions, Conformity and Deviance, Reference Groups",
        estimatedMinutes: 180,
        difficulty: 3,
      },
      {
        id: "mead",
        name: "Mead - Self and Identity",
        estimatedMinutes: 120,
        difficulty: 2,
      },
    ],
  },
  {
    id: "stratification-and-mobility",
    name: "Stratification and Mobility",
    subtopics: [
      {
        id: "concepts-stratification",
        name: "Concepts - Equality, Inequality, Hierarchy, Exclusion, Poverty and Deprivation",
        estimatedMinutes: 150,
        difficulty: 2,
      },
      {
        id: "theories-stratification",
        name: "Theories of Stratification - Structural Functionalist, Marxist, Weberian",
        estimatedMinutes: 180,
        difficulty: 3,
      },
      {
        id: "dimensions-stratification",
        name: "Dimensions - Class, Status Groups, Gender, Ethnicity and Race",
        estimatedMinutes: 150,
        difficulty: 2,
      },
      {
        id: "social-mobility",
        name: "Social Mobility - Open and Closed Systems, Types, Sources and Causes",
        estimatedMinutes: 150,
        difficulty: 2,
      },
    ],
  },
  {
    id: "works-and-economic-life",
    name: "Works and Economic Life",
    subtopics: [
      {
        id: "social-organization-work",
        name: "Social organization of work in different societies - Slave, Feudal, Capitalist",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "formal-informal-organization",
        name: "Formal and informal organization of work",
        estimatedMinutes: 60,
        difficulty: 1,
      },
      {
        id: "labour-and-society",
        name: "Labour and society",
        estimatedMinutes: 90,
        difficulty: 2,
      },
    ],
  },
  {
    id: "politics-and-society",
    name: "Politics and Society",
    subtopics: [
      {
        id: "sociological-theories-power",
        name: "Sociological theories of power",
        estimatedMinutes: 150,
        difficulty: 3,
      },
      {
        id: "power-elite-bureaucracy",
        name: "Power elite, bureaucracy, pressure groups, political parties",
        estimatedMinutes: 150,
        difficulty: 2,
      },
      {
        id: "nation-state-citizenship-democracy",
        name: "Nation, state, citizenship, democracy, civil society, ideology",
        estimatedMinutes: 150,
        difficulty: 2,
      },
      {
        id: "protest-agitation-social-movements",
        name: "Protest, agitation, social movements, collective action, revolution",
        estimatedMinutes: 150,
        difficulty: 2,
      },
    ],
  },
  {
    id: "religion-and-society",
    name: "Religion and Society",
    subtopics: [
      {
        id: "sociological-theories-religion",
        name: "Sociological theories of religion",
        estimatedMinutes: 150,
        difficulty: 3,
      },
      {
        id: "types-religious-practices",
        name: "Types of religious practices - Animism, Monotheism, Pluralism, Sects, Cults",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "religion-modern-society",
        name: "Religion in modern society - Religion and science, Secularization, Fundamentalism, Pluralism",
        estimatedMinutes: 150,
        difficulty: 2,
      },
    ],
  },
  {
    id: "systems-of-kinship",
    name: "Systems of Kinship",
    subtopics: [
      {
        id: "family-household-marriage",
        name: "Family, household, marriage",
        estimatedMinutes: 120,
        difficulty: 1,
      },
      {
        id: "types-and-forms-family",
        name: "Types and forms of family",
        estimatedMinutes: 90,
        difficulty: 1,
      },
      {
        id: "lineage-and-descent",
        name: "Lineage and descent",
        estimatedMinutes: 90,
        difficulty: 2,
      },
      {
        id: "patriarchy-sexual-division-labour",
        name: "Patriarchy and sexual division of labour",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "contemporary-trends",
        name: "Contemporary trends",
        estimatedMinutes: 120,
        difficulty: 2,
      },
    ],
  },
  {
    id: "social-change-modern-society",
    name: "Social Change in Modern Society",
    subtopics: [
      {
        id: "sociological-theories-change",
        name: "Sociological theories of social change",
        estimatedMinutes: 150,
        difficulty: 3,
      },
      {
        id: "development-and-dependency",
        name: "Development and dependency",
        estimatedMinutes: 120,
        difficulty: 3,
      },
      {
        id: "agents-social-change",
        name: "Agents of social change",
        estimatedMinutes: 60,
        difficulty: 1,
      },
      {
        id: "education-and-social-change",
        name: "Education and social change",
        estimatedMinutes: 90,
        difficulty: 1,
      },
      {
        id: "science-technology-social-change",
        name: "Science, technology and social change",
        estimatedMinutes: 90,
        difficulty: 2,
      },
    ],
  },
],
  },
  {
    id: "sociology2",
    type: "OPTIONAL",
    paper: "PAPER_2",
    name: "Sociology Paper 2",

    topics: [
  {
    id: "perspective-study-indian-society",
    name: "Perspective on the study of Indian Society",
    subtopics: [
      {
        id: "sociology-background-india",
        name: "Sociology Background in India",
        estimatedMinutes: 90,
        difficulty: 1,
      },
      {
        id: "indological-perspective",
        name: "Indological Perspective on Study of Indian Society",
        estimatedMinutes: 90,
        difficulty: 2,
      },
      {
        id: "gs-ghurye-indology",
        name: "Govind Sadashiv Ghurye (1893-1984) and Indology",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "ghurye-study-indian-society",
        name: "Ghurye's Study of Indian Society",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "structural-functionalism-india",
        name: "Structural Functionalism Tradition in India",
        estimatedMinutes: 120,
        difficulty: 3,
      },
      {
        id: "dominant-caste",
        name: "Dominant Caste",
        estimatedMinutes: 90,
        difficulty: 2,
      },
      {
        id: "sanskritisation",
        name: "Sanskritisation",
        estimatedMinutes: 90,
        difficulty: 2,
      },
      {
        id: "westernisation",
        name: "Westernisation",
        estimatedMinutes: 90,
        difficulty: 1,
      },
      {
        id: "mn-srinivas-contribution",
        name: "MN Srinivas contribution",
        estimatedMinutes: 150,
        difficulty: 3,
      },
      {
        id: "marxist-approach-indian-nationalism",
        name: "Indian Nationalism according to Marxist approach",
        estimatedMinutes: 150,
        difficulty: 3,
      },
      {
        id: "ar-desai-central-ideas",
        name: "Central ideas of AR Desai",
        estimatedMinutes: 150,
        difficulty: 3,
      },
    ],
  },
  {
    id: "modernisation-indian-tradition",
    name: "Modernisation of Indian Tradition",
    subtopics: [
      {
        id: "modernisation-indian-tradition-intro",
        name: "Modernisation of Indian Tradition",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "yogendra-singh-modernisation",
        name: "Yogendra Singh on modernisation",
        estimatedMinutes: 120,
        difficulty: 3,
      },
      {
        id: "little-and-great-traditions",
        name: "Little and Great traditions",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "ranajit-guha-subaltern",
        name: "Ranajit Guha",
        estimatedMinutes: 120,
        difficulty: 3,
      },
      {
        id: "social-evils-colonial-india",
        name: "Social evils present during Colonial India",
        estimatedMinutes: 90,
        difficulty: 1,
      },
      {
        id: "colonial-administration",
        name: "Administration during Colonial times",
        estimatedMinutes: 90,
        difficulty: 1,
      },
      {
        id: "social-reform-movements",
        name: "Social Reform Movements",
        estimatedMinutes: 120,
        difficulty: 1,
      },
      {
        id: "limitations-social-reforms",
        name: "Limitation of social reforms",
        estimatedMinutes: 90,
        difficulty: 2,
      },
      {
        id: "traditions-modernity-social-change",
        name: "Traditions, Modernity and Social Change",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "yogendra-singh-tradition",
        name: "Yogendra Singh on tradition",
        estimatedMinutes: 120,
        difficulty: 3,
      },
      {
        id: "unchanged-traditions",
        name: "Unchanged traditions over time",
        estimatedMinutes: 90,
        difficulty: 2,
      },
      {
        id: "fusion-modernisation-traditions",
        name: "Fusion of modernisation and traditions",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "criticism-modernisation",
        name: "Criticism about modernisation",
        estimatedMinutes: 90,
        difficulty: 2,
      },
    ],
  },
  {
    id: "rural-agrarian-social-structure",
    name: "Rural and Agrarian Social Structure",
    subtopics: [
      {
        id: "idea-indian-village-studies",
        name: "Idea of Indian village and village studies",
        estimatedMinutes: 150,
        difficulty: 2,
      },
      {
        id: "rural-agrarian-unrest-present",
        name: "Rural and agrarian unrest in present times",
        estimatedMinutes: 150,
        difficulty: 3,
      },
      {
        id: "divisions-rural-society",
        name: "Divisons in rural society",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "mn-srinivas-village-study",
        name: "MN Srinivas study of indian village",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "sc-dube-village-study",
        name: "SC Dube study of indian village",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "andre-beteille-village-study",
        name: "Andre Beteille study of indian village",
        estimatedMinutes: 150,
        difficulty: 3,
      },
      {
        id: "other-village-studies",
        name: "Other village studies",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "evolution-land-tenure-system",
        name: "Evolution of land tenure system",
        estimatedMinutes: 150,
        difficulty: 2,
      },
    ],
  },
  {
    id: "caste-system",
    name: "Caste System",
    subtopics: [
      {
        id: "caste-system-introduction",
        name: "Introduction",
        estimatedMinutes: 60,
        difficulty: 1,
      },
      {
        id: "views-different-thinkers-caste",
        name: "Views of different thinkers",
        estimatedMinutes: 180,
        difficulty: 3,
      },
      {
        id: "racial-theory-caste",
        name: "Racial theory of caste",
        estimatedMinutes: 90,
        difficulty: 2,
      },
      {
        id: "caste-system-features",
        name: "Caste system features",
        estimatedMinutes: 120,
        difficulty: 1,
      },
      {
        id: "discrete-caste-muddled-hierarchies",
        name: "Discrete caste and muddled hierarchies",
        estimatedMinutes: 150,
        difficulty: 3,
      },
      {
        id: "inter-caste-conflicts",
        name: "Inter-caste conflicts",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "intra-caste-conflicts",
        name: "Intra-caste conflicts",
        estimatedMinutes: 90,
        difficulty: 2,
      },
      {
        id: "hierarchy-to-differentiation",
        name: "Hierarchy to differentiation",
        estimatedMinutes: 120,
        difficulty: 3,
      },
      {
        id: "annihilation-of-caste-ambedkar",
        name: "Annihillation of caste BR Ambedkar",
        estimatedMinutes: 180,
        difficulty: 3,
      },
      {
        id: "ambedkar-vs-gandhi-caste",
        name: "Ambedkar vs Gandhi on caste",
        estimatedMinutes: 150,
        difficulty: 3,
      },
      {
        id: "caste-ram-manohar-lohia",
        name: "Caste as per Ram Manohar Lohia",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "caste-structure-different-religions",
        name: "Caste ideology and structure in different religions",
        estimatedMinutes: 150,
        difficulty: 3,
      },
      {
        id: "untouchability",
        name: "Untouchability",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "gandhi-and-untouchability",
        name: "Gandhi and Untouchability",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "caste-and-politics",
        name: "Caste and Politics",
        estimatedMinutes: 150,
        difficulty: 2,
      },
      {
        id: "caste-and-democracy",
        name: "Caste and Democracy",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "dalit-consciousness",
        name: "Dalit Consciousness",
        estimatedMinutes: 150,
        difficulty: 3,
      },
      {
        id: "sanskritization-de-sanskritization",
        name: "Sanskritization and De-sanskritization",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "caste-and-class",
        name: "Caste and Class",
        estimatedMinutes: 150,
        difficulty: 3,
      },
      {
        id: "caste-and-tribes",
        name: "Caste and tribes",
        estimatedMinutes: 120,
        difficulty: 2,
      },
    ],
  },
  {
    id: "tribal-communities-india",
    name: "Tribal Communities in India",
    subtopics: [
      {
        id: "definitions-tribals",
        name: "Definitions of tribals",
        estimatedMinutes: 90,
        difficulty: 1,
      },
      {
        id: "main-features-tribal-groups",
        name: "Main features of Tribal groups",
        estimatedMinutes: 90,
        difficulty: 1,
      },
      {
        id: "distribution-indian-tribes",
        name: "Distribution of Indian tribes",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "ghurye-vs-elvin",
        name: "GS Ghurye vs V Elvin",
        estimatedMinutes: 150,
        difficulty: 3,
      },
      {
        id: "different-policies-tribals",
        name: "Different policies",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "tribal-culture-discontent-identity",
        name: "Tribal culture discontent identity and assertions",
        estimatedMinutes: 150,
        difficulty: 3,
      },
      {
        id: "pvtgs",
        name: "PVTGs",
        estimatedMinutes: 100,
        difficulty: 2,
      },
      {
        id: "ethnicity-regionalism-issue",
        name: "Ethnicity and Regionalism issue",
        estimatedMinutes: 150,
        difficulty: 3,
      },
      {
        id: "tribe-and-caste",
        name: "Tribe and Caste",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "tribe-and-class",
        name: "Tribe and Class",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "stratification-between-tribes",
        name: "Stratification between tribes",
        estimatedMinutes: 120,
        difficulty: 3,
      },
      {
        id: "tribal-problems",
        name: "Tribal problems",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "mitigation-mobility-unity",
        name: "Mitigation mobility an unity",
        estimatedMinutes: 120,
        difficulty: 2,
      },
    ],
  },
  {
    id: "social-classes-india",
    name: "Social Classes in India",
    subtopics: [
      {
        id: "class-concept-india",
        name: "Class",
        estimatedMinutes: 90,
        difficulty: 1,
      },
      {
        id: "agrarian-class-structure",
        name: "Agrarian class structure",
        estimatedMinutes: 150,
        difficulty: 3,
      },
      {
        id: "industrial-class-structure",
        name: "Industrial class structure",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "middle-class-india",
        name: "Middle class",
        estimatedMinutes: 150,
        difficulty: 2,
      },
    ],
  },
  {
    id: "system-kinship-india",
    name: "System of Kinship in India",
    subtopics: [
      {
        id: "lineage-descent-india",
        name: "Lineage and Descent",
        estimatedMinutes: 90,
        difficulty: 2,
      },
      {
        id: "kinship-system-india-regions",
        name: "Kinship system in India",
        estimatedMinutes: 150,
        difficulty: 2,
      },
      {
        id: "family-marriage-india",
        name: "Family and Marriage in India",
        estimatedMinutes: 150,
        difficulty: 2,
      },
      {
        id: "patriarchy-entitlements-division-labour",
        name: "Patriarchy Entitlements and sexual division of labour",
        estimatedMinutes: 150,
        difficulty: 3,
      },
      {
        id: "intergenerational-challenges",
        name: "Intergenerational Challenges",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "uniform-civil-code",
        name: "Common civil code",
        estimatedMinutes: 150,
        difficulty: 3,
      },
      {
        id: "new-changes-kinship",
        name: "New changes",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "entitlement-transgender-lgbtq",
        name: "Entitlement of Transgender and LGBTQ",
        estimatedMinutes: 150,
        difficulty: 3,
      },
    ],
  },
  {
    id: "religion-and-society-india",
    name: "Religion and Society",
    subtopics: [
      {
        id: "religious-community",
        name: "Religious community",
        estimatedMinutes: 120,
        difficulty: 1,
      },
      {
        id: "problems-religious-minority",
        name: "Problems of religious minority",
        estimatedMinutes: 150,
        difficulty: 2,
      },
      {
        id: "secularism-in-india-concept",
        name: "Secularism in India",
        estimatedMinutes: 180,
        difficulty: 3,
      },
    ],
  },
  {
    id: "vision-social-change-india",
    name: "Vision of Social change in India",
    subtopics: [
      {
        id: "ideas-development-planning-mixed-economy",
        name: "Ideas of development planning and mixed economy",
        estimatedMinutes: 150,
        difficulty: 2,
      },
      {
        id: "modernisation-social-change-vision",
        name: "Modernisation and social change",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "approaches-social-change-india",
        name: "Approaches to Social change in India",
        estimatedMinutes: 150,
        difficulty: 3,
      },
      {
        id: "constitution-law-social-change",
        name: "Constitution Law and Social change",
        estimatedMinutes: 180,
        difficulty: 3,
      },
      {
        id: "education-and-social-change-india",
        name: "Education and social change",
        estimatedMinutes: 90,
        difficulty: 1,
      },
    ],
  },
  {
    id: "rural-agrarian-transformations-india",
    name: "Rural and Agrarian Transformations in India",
    subtopics: [
      {
        id: "transformations-introduction",
        name: "Introduction",
        estimatedMinutes: 60,
        difficulty: 1,
      },
      {
        id: "poverty-alleviation-schemes-rural",
        name: "Poverty Alleviation Schemes",
        estimatedMinutes: 150,
        difficulty: 2,
      },
      {
        id: "changing-modes-production-agriculture",
        name: "Changing modes of production in Indian agriculture",
        estimatedMinutes: 180,
        difficulty: 3,
      },
      {
        id: "problems-rural-labour",
        name: "Problems of rural labour",
        estimatedMinutes: 150,
        difficulty: 2,
      },
    ],
  },
  {
    id: "industrialisation-urbanisation-india",
    name: "Industrialisation and urbanisation in India",
    subtopics: [
      {
        id: "industrialisation-process",
        name: "Industrialisation",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "growth-urban-settlements",
        name: "Growth of urban settlements",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "working-class-india",
        name: "Working class in India",
        estimatedMinutes: 150,
        difficulty: 2,
      },
      {
        id: "informal-sector-urban",
        name: "Informal Sector",
        estimatedMinutes: 150,
        difficulty: 3,
      },
      {
        id: "slums-deprivation-urban-area",
        name: "Slums and Deprivation in Urban area",
        estimatedMinutes: 120,
        difficulty: 2,
      },
    ],
  },
  {
    id: "politics-and-society-india",
    name: "Politics and Society",
    subtopics: [
      {
        id: "nation-democracy-citizenship",
        name: "Nation Democracy and Citizenship",
        estimatedMinutes: 150,
        difficulty: 3,
      },
      {
        id: "parties-pressure-groups-elites",
        name: "Political parties Pressure Groups and Social Elites",
        estimatedMinutes: 180,
        difficulty: 2,
      },
      {
        id: "regionalism-decentralisation-power",
        name: "Regionalism and decentralisation of power",
        estimatedMinutes: 150,
        difficulty: 2,
      },
      {
        id: "secularisation-process",
        name: "Secularisation",
        estimatedMinutes: 120,
        difficulty: 3,
      },
    ],
  },
  {
    id: "social-movements-modern-india",
    name: "Social Movements in Modern India",
    subtopics: [
      {
        id: "peasant-farmers-movements",
        name: "Peasant and Farmers Movements",
        estimatedMinutes: 180,
        difficulty: 2,
      },
      {
        id: "women-movement-india",
        name: "Women movement in India",
        estimatedMinutes: 150,
        difficulty: 2,
      },
      {
        id: "dalit-movements-india",
        name: "Dalit movements",
        estimatedMinutes: 150,
        difficulty: 3,
      },
      {
        id: "backward-class-movement",
        name: "Backward class movement",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "ethnic-movements-india",
        name: "Ethnic movements",
        estimatedMinutes: 120,
        difficulty: 3,
      },
      {
        id: "identity-movements",
        name: "Identity movements",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "new-social-movements",
        name: "New movements",
        estimatedMinutes: 150,
        difficulty: 3,
      },
    ],
  },
  {
    id: "population-dynamics-india",
    name: "Population Dynamics",
    subtopics: [
      {
        id: "population-growth-composition-distribution",
        name: "Population growth Composition and Distribution",
        estimatedMinutes: 150,
        difficulty: 2,
      },
      {
        id: "components-population-growth",
        name: "Components of Population Growth",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "population-policy-family-planning",
        name: "Population Policy and Family Planning",
        estimatedMinutes: 150,
        difficulty: 2,
      },
      {
        id: "emerging-population-issues",
        name: "Emerging Issues",
        estimatedMinutes: 120,
        difficulty: 3,
      },
    ],
  },
  {
    id: "challenges-social-transformation",
    name: "Challenges of Social Transformation",
    subtopics: [
      {
        id: "crisis-of-development",
        name: "Crisis of development",
        estimatedMinutes: 150,
        difficulty: 3,
      },
      {
        id: "poverty-deprivation-inequality",
        name: "Poverty Deprivation and Inequality",
        estimatedMinutes: 150,
        difficulty: 2,
      },
      {
        id: "violence-against-women",
        name: "Violence against Women",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "caste-conflicts-transformation",
        name: "Caste Conflicts",
        estimatedMinutes: 150,
        difficulty: 3,
      },
      {
        id: "ethnic-conflicts-transformation",
        name: "Ethnic conficts",
        estimatedMinutes: 150,
        difficulty: 3,
      },
      {
        id: "illiteracy-disparities-education",
        name: "Illiteracy and disparities in education",
        estimatedMinutes: 120,
        difficulty: 1,
      },
    ],
  },
],
  },

  {
    id: "mathematics1",
    type: "OPTIONAL",
    paper: "PAPER_1",
    name: "Mathematics Paper 1",

    topics: [
      {
    id: "linear-algebra",
    name: "Linear Algebra",
    subtopics: [
      {
        id: "vector-spaces-over-r-and-c",
        name: "Vector spaces over R and C",
        estimatedMinutes: 45,
        difficulty: 2,
      },
      {
        id: "linear-dependence-and-independence",
        name: "Linear dependence and independence",
        estimatedMinutes: 30,
        difficulty: 2,
      },
      {
        id: "subspaces",
        name: "Subspaces",
        estimatedMinutes: 90,
        difficulty: 3,
      },
      {
        id: "bases-and-dimensions",
        name: "Bases, dimensions",
        estimatedMinutes: 90,
        difficulty: 4,
      },
      {
        id: "linear-transformations",
        name: "Linear transformations",
        estimatedMinutes: 90,
        difficulty: 3,
      },
      {
        id: "rank-and-nullity",
        name: "Rank and nullity",
        estimatedMinutes: 90,
        difficulty: 4,
      },
      {
        id: "matrix-of-a-linear-transformation",
        name: "Matrix of a linear transformation",
        estimatedMinutes: 120,
        difficulty: 5,
      },
      {
        id: "algebra-of-matrices",
        name: "Algebra of Matrices",
        estimatedMinutes: 30,
        difficulty: 1,
      },
      {
        id: "row-and-column-reduction-echelon-form",
        name: "Row and column reduction, Echelon form",
        estimatedMinutes: 45,
        difficulty: 2,
      },
      {
        id: "congruences-and-similarity",
        name: "Congruences and similarity",
        estimatedMinutes: 60,
        difficulty: 4,
      },
      {
        id: "rank-of-a-matrix",
        name: "Rank of a matrix",
        estimatedMinutes: 45,
        difficulty: 2,
      },
      {
        id: "inverse-of-a-matrix",
        name: "Inverse of a matrix",
        estimatedMinutes: 30,
        difficulty: 1,
      },
      {
        id: "solution-of-system-of-linear-equations",
        name: "Solution of system of linear equations",
        estimatedMinutes: 60,
        difficulty: 3,
      },
      {
        id: "eigenvalues-and-eigenvectors",
        name: "Eigenvalues and eigenvectors",
        estimatedMinutes: 90,
        difficulty: 3,
      },
      {
        id: "characteristic-polynomial-cayley-hamilton-theorem",
        name: "Characteristic polynomial, Cayley-Hamilton theorem",
        estimatedMinutes: 75,
        difficulty: 3,
      },
      {
        id: "symmetric-skew-symmetric-orthogonal-matrices",
        name: "Symmetric, skew-symmetric, orthogonal matrices and their eigenvalues",
        estimatedMinutes: 60,
        difficulty: 2,
      },
      {
        id: "hermitian-skew-hermitian-unitary-matrices",
        name: "Hermitian, skew-Hermitian, unitary matrices and their eigenvalues",
        estimatedMinutes: 75,
        difficulty: 3,
      },
    ],
  },
  
  {
    id: "calculus",
    name: "Calculus",
    subtopics: [
      {
        id: "real-numbers-functions-real-variable",
        name: "Real numbers, functions of a real variable",
        estimatedMinutes: 60,
        difficulty: 2,
      },
      {
        id: "limits-continuity-differentiability",
        name: "Limits, continuity, differentiability",
        estimatedMinutes: 120,
        difficulty: 3,
      },
      {
        id: "mvt-taylors-theorem-remainders",
        name: "Mean-value theorem, Taylors theorem with remainders",
        estimatedMinutes: 90,
        difficulty: 4,
      },
      {
        id: "indeterminate-forms",
        name: "Indeterminate forms",
        estimatedMinutes: 60,
        difficulty: 2,
      },
      {
        id: "maxima-and-minima-single",
        name: "Maxima and minima (Single Variable)",
        estimatedMinutes: 90,
        difficulty: 3,
      },
      {
        id: "asymptotes-curve-tracing",
        name: "Asymptotes; Curve tracing",
        estimatedMinutes: 120,
        difficulty: 3,
      },
      {
        id: "multivariable-limits-continuity-partial",
        name: "Functions of 2/3 variables: Limits, continuity, partial derivatives",
        estimatedMinutes: 120,
        difficulty: 4,
      },
      {
        id: "maxima-minima-lagrange",
        name: "Maxima and minima, Lagranges method of multipliers",
        estimatedMinutes: 120,
        difficulty: 4,
      },
      {
        id: "jacobian",
        name: "Jacobian",
        estimatedMinutes: 75,
        difficulty: 3,
      },
      {
        id: "riemann-integrals-indefinite",
        name: "Riemanns definition of definite integrals; Indefinite integrals",
        estimatedMinutes: 150,
        difficulty: 5,
      },
      {
        id: "infinite-and-improper-integrals",
        name: "Infinite and improper integral",
        estimatedMinutes: 180,
        difficulty: 4,
      },
      {
        id: "double-and-triple-integrals",
        name: "Double and triple integrals (evaluation techniques only)",
        estimatedMinutes: 120,
        difficulty: 3,
      },
      {
        id: "areas-surfaces-volumes",
        name: "Areas, surface and volumes",
        estimatedMinutes: 120,
        difficulty: 4,
      },
    ],
  },
  {
    id: "analytic-geometry",
    name: "Analytic Geometry (3D)",
    subtopics: [
      {
        id: "cartesian-polar-coordinates-and-plane",
        name: "Cartesian and polar coordinates in 3D & The Plane",
        estimatedMinutes: 90,
        difficulty: 2,
      },
      {
        id: "straight-lines-shortest-distance",
        name: "Straight lines and Shortest distance between two skew lines",
        estimatedMinutes: 90,
        difficulty: 3,
      },
      {
        id: "sphere",
        name: "Sphere (Tangent planes, orthogonal spheres, radical plane)",
        estimatedMinutes: 150,
        difficulty: 3,
      },
      {
        id: "cone",
        name: "Cone (Enveloping cone, mutually perpendicular generators)",
        estimatedMinutes: 150,
        difficulty: 3,
      },
      {
        id: "cylinder",
        name: "Cylinder (Right circular and enveloping cylinder)",
        estimatedMinutes: 150,
        difficulty: 2,
      },
      {
        id: "paraboloid",
        name: "Paraboloid (Elliptic and hyperbolic, normals)",
        estimatedMinutes: 150,
        difficulty: 3,
      },
      {
        id: "ellipsoid",
        name: "Ellipsoid (Director sphere, normals, conjugate diameters)",
        estimatedMinutes: 150,
        difficulty: 4,
      },
      {
        id: "hyperboloid",
        name: "Hyperboloid of one and two sheets (Properties and Generating Lines)",
        estimatedMinutes: 150,
        difficulty: 4,
      },
      {
        id: "reduction-to-canonical-forms",
        name: "Second degree equations in 3 variables: Reduction to Canonical forms",
        estimatedMinutes: 180,
        difficulty: 5,
      },
    ],
  },

  {
    id: "ordinary-differential-equations",
    name: "Ordinary Differential Equations",
    subtopics: [
      {
        id: "formulation-of-differential-equations",
        name: "Formulation of differential equations",
        estimatedMinutes: 30,
        difficulty: 1,
      },
      {
        id: "first-order-first-degree-integrating-factor",
        name: "Equations of first order and first degree, integrating factor",
        estimatedMinutes: 120,
        difficulty: 3,
      },
      {
        id: "orthogonal-trajectory",
        name: "Orthogonal trajectory",
        estimatedMinutes: 60,
        difficulty: 2,
      },
      {
        id: "first-order-not-first-degree-clairauts-singular",
        name: "Equations of first order but not of first degree, Clairauts equation, singular solution",
        estimatedMinutes: 120,
        difficulty: 3,
      },
      {
        id: "higher-order-linear-constant-coefficients",
        name: "Second and higher order linear equations with constant coefficients (CF and PI)",
        estimatedMinutes: 150,
        difficulty: 3,
      },
      {
        id: "second-order-variable-coefficients-euler-cauchy",
        name: "Second order linear equations with variable coefficients, Euler-Cauchy equation",
        estimatedMinutes: 90,
        difficulty: 3,
      },
      {
        id: "variation-of-parameters-one-solution-known",
        name: "Complete solution when one solution is known & Method of variation of parameters",
        estimatedMinutes: 120,
        difficulty: 4,
      },
      {
        id: "laplace-inverse-laplace-properties",
        name: "Laplace and Inverse Laplace transforms, properties, and elementary functions",
        estimatedMinutes: 150,
        difficulty: 3,
      },
      {
        id: "application-ivp-laplace",
        name: "Application to initial value problems for 2nd order linear equations with constant coefficients",
        estimatedMinutes: 90,
        difficulty: 4,
      },
    ],
  },

  {
    id: "vector-analysis",
    name: "Vector Analysis",
    subtopics: [
      {
        id: "scalar-vector-fields-differentiation",
        name: "Scalar and vector fields, differentiation of vector field of a scalar variable",
        estimatedMinutes: 60,
        difficulty: 2,
      },
      {
        id: "gradient-divergence-curl-coordinates",
        name: "Gradient, divergence and curl in cartesian and cylindrical coordinates",
        estimatedMinutes: 90,
        difficulty: 3,
      },
      {
        id: "higher-order-vector-identities-equations",
        name: "Higher order derivatives; Vector identities and vector equation",
        estimatedMinutes: 90,
        difficulty: 4,
      },
      {
        id: "geometry-curves-curvature-torsion-frenet",
        name: "Application to geometry: Curves in space, curvature and torsion; Serret-Frenet's formulae",
        estimatedMinutes: 150,
        difficulty: 4,
      },
      {
        id: "greens-theorem",
        name: "Greens Theorem in a plane",
        estimatedMinutes: 90,
        difficulty: 3,
      },
      {
        id: "gauss-divergence-theorem",
        name: "Gauss Divergence Theorem",
        estimatedMinutes: 90,
        difficulty: 4,
      },
      {
        id: "stokes-theorem",
        name: "Stokes Theorem",
        estimatedMinutes: 90,
        difficulty: 4,
      },
    ],
  },

  {
    id: "dynamics-and-statics",
    name: "Dynamics and Statics",
    subtopics: [
      {
        id: "rectilinear-motion",
        name: "Rectilinear motion",
        estimatedMinutes: 90,
        difficulty: 2,
      },
      {
        id: "simple-harmonic-motion",
        name: "Simple harmonic motion",
        estimatedMinutes: 90,
        difficulty: 2,
      },
      {
        id: "motion-in-a-plane",
        name: "Motion in a plane (Radial/Transverse & Tangential/Normal)",
        estimatedMinutes: 120,
        difficulty: 3,
      },
      {
        id: "projectiles",
        name: "Projectiles",
        estimatedMinutes: 150,
        difficulty: 2,
      },
      {
        id: "constrained-motion",
        name: "Constrained motion",
        estimatedMinutes: 120,
        difficulty: 4,
      },
      {
        id: "work-energy-conservation",
        name: "Work and energy, conservation of energy",
        estimatedMinutes: 90,
        difficulty: 2,
      },
      {
        id: "central-forces-keplers-laws",
        name: "Keplers laws, orbits under central forces",
        estimatedMinutes: 150,
        difficulty: 4,
      },
      {
        id: "equilibrium-system-of-particles",
        name: "Equilibrium of a system of particles",
        estimatedMinutes: 90,
        difficulty: 2,
      },
      {
        id: "work-and-potential-energy-statics",
        name: "Work and potential energy",
        estimatedMinutes: 90,
        difficulty: 2,
      },
      {
        id: "friction",
        name: "Friction",
        estimatedMinutes: 120,
        difficulty: 3,
      },
      {
        id: "common-catenary",
        name: "Common catenary",
        estimatedMinutes: 120,
        difficulty: 3,
      },
      {
        id: "principle-of-virtual-work",
        name: "Principle of virtual work",
        estimatedMinutes: 150,
        difficulty: 4,
      },
      {
        id: "stability-of-equilibrium",
        name: "Stability of equilibrium",
        estimatedMinutes: 120,
        difficulty: 4,
      },
      {
        id: "equilibrium-of-forces-in-3d",
        name: "Equilibrium of forces in three dimensions",
        estimatedMinutes: 180,
        difficulty: 5,
      },
    ],
  }
    ],
  },

  {
    id: "mathematics2",
    type: "OPTIONAL",
    paper: "PAPER_2",
    name: "Mathematics Paper 2",

    topics: [
      {
    id: "modern-algebra",
    name: "Modern Algebra",
    subtopics: [
      {
        id: "groups-subgroups-cyclic-groups",
        name: "Groups, subgroups, cyclic groups",
        estimatedMinutes: 120,
        difficulty: 3,
      },
      {
        id: "cosets-lagranges-theorem",
        name: "Cosets, Lagranges Theorem",
        estimatedMinutes: 120,
        difficulty: 3,
      },
      {
        id: "normal-subgroups-quotient-groups",
        name: "Normal subgroups, quotient groups",
        estimatedMinutes: 150,
        difficulty: 4,
      },
      {
        id: "homomorphism-isomorphism-theorems",
        name: "Homomorphism of groups, basic isomorphism theorems",
        estimatedMinutes: 180,
        difficulty: 5,
      },
      {
        id: "permutation-groups",
        name: "Permutation groups",
        estimatedMinutes: 120,
        difficulty: 3,
      },
      {
        id: "cayleys-theorem",
        name: "Cayleys theorem",
        estimatedMinutes: 90,
        difficulty: 3,
      },
      {
        id: "rings-subrings-ideals",
        name: "Rings, subrings and ideals",
        estimatedMinutes: 150,
        difficulty: 4,
      },
      {
        id: "homomorphisms-of-rings",
        name: "Homomorphisms of rings",
        estimatedMinutes: 120,
        difficulty: 4,
      },
      {
        id: "integral-domains-pid",
        name: "Integral domains, principal ideal domains (PID)",
        estimatedMinutes: 150,
        difficulty: 4,
      },
      {
        id: "euclidean-domains-ufd",
        name: "Euclidean domains and unique factorization domains (UFD)",
        estimatedMinutes: 180,
        difficulty: 5,
      },
      {
        id: "fields-quotient-fields",
        name: "Fields, quotient fields",
        estimatedMinutes: 120,
        difficulty: 3,
      },
    ],
  },
  
  {
    id: "real-analysis",
    name: "Real Analysis",
    subtopics: [
      {
        id: "real-number-system-lub",
        name: "Real number system as an ordered field with least upper bound property",
        estimatedMinutes: 90,
        difficulty: 3,
      },
      {
        id: "sequences-cauchy-completeness",
        name: "Sequences, limit of a sequence, Cauchy sequence, completeness of real line",
        estimatedMinutes: 150,
        difficulty: 4,
      },
      {
        id: "series-convergence-rearrangement",
        name: "Series & Convergence (Absolute/Conditional, Complex terms, Rearrangement)",
        estimatedMinutes: 150,
        difficulty: 4,
      },
      {
        id: "continuity-uniform-continuity-compact-sets",
        name: "Continuity, uniform continuity, properties of continuous functions on compact sets",
        estimatedMinutes: 150,
        difficulty: 4,
      },
      {
        id: "riemann-improper-integrals-fundamental-theorems",
        name: "Riemann integral, improper integrals; Fundamental theorems of integral calculus",
        estimatedMinutes: 180,
        difficulty: 5,
      },
      {
        id: "uniform-convergence-sequences-series-functions",
        name: "Sequences and series of functions (Uniform convergence, continuity, differentiability, integrability)",
        estimatedMinutes: 180,
        difficulty: 5,
      },
      {
        id: "several-variables-partial-derivatives-maxima-minima",
        name: "Functions of several variables: Partial derivatives, maxima and minima",
        estimatedMinutes: 120,
        difficulty: 3,
      },
    ],
  },

  {
    id: "complex-analysis",
    name: "Complex Analysis",
    subtopics: [
      {
        id: "analytic-function-cauchy-riemann",
        name: "Analytic function, Cauchy-Riemann equations",
        estimatedMinutes: 90,
        difficulty: 2,
      },
      {
        id: "cauchys-theorem-integral-formula",
        name: "Cauchy's theorem, Cauchy's integral formula",
        estimatedMinutes: 120,
        difficulty: 3,
      },
      {
        id: "power-series-taylors-series",
        name: "Power series, representation of an analytic function, Taylors series",
        estimatedMinutes: 90,
        difficulty: 3,
      },
      {
        id: "singularities-laurents-series",
        name: "Singularities; Laurents series",
        estimatedMinutes: 120,
        difficulty: 4,
      },
      {
        id: "cauchys-residue-theorem",
        name: "Cauchys residue theorem",
        estimatedMinutes: 120,
        difficulty: 4,
      },
      {
        id: "contour-integration",
        name: "Contour integration",
        estimatedMinutes: 180,
        difficulty: 5,
      },
    ],
  },

  {
    id: "linear-programming",
    name: "Linear Programming",
    subtopics: [
      {
        id: "lpp-formulation-basic-solutions",
        name: "LPP formulation, basic solution, basic feasible solution and optimal solution",
        estimatedMinutes: 90,
        difficulty: 2,
      },
      {
        id: "graphical-method",
        name: "Graphical method of solutions",
        estimatedMinutes: 60,
        difficulty: 1,
      },
      {
        id: "simplex-method",
        name: "Simplex method of solutions (includes Big-M and Two-Phase methods)",
        estimatedMinutes: 180,
        difficulty: 3,
      },
      {
        id: "duality",
        name: "Duality (Writing duals, Dual Simplex, Theorems of Duality)",
        estimatedMinutes: 120,
        difficulty: 3,
      },
      {
        id: "transportation-problem",
        name: "Transportation problems (Initial BFS & MODI method for optimality)",
        estimatedMinutes: 120,
        difficulty: 2,
      },
      {
        id: "assignment-problem",
        name: "Assignment problems (Hungarian Method)",
        estimatedMinutes: 90,
        difficulty: 2,
      },
    ],
  },

  {
    id: "partial-differential-equations",
    name: "Partial Differential Equations",
    subtopics: [
      {
        id: "formulation-of-pdes-family-of-surfaces",
        name: "Family of surfaces in 3D and formulation of PDEs",
        estimatedMinutes: 60,
        difficulty: 2,
      },
      {
        id: "quasilinear-pdes-cauchys-characteristics",
        name: "Solution of quasilinear PDEs of first order, Cauchys method of characteristics",
        estimatedMinutes: 150,
        difficulty: 3,
      },
      {
        id: "second-order-linear-constant-coefficients",
        name: "Linear PDEs of the second order with constant coefficients (CF and PI)",
        estimatedMinutes: 180,
        difficulty: 3,
      },
      {
        id: "classification-and-canonical-form",
        name: "Classification of 2nd order PDEs and reduction to canonical form",
        estimatedMinutes: 150,
        difficulty: 4,
      },
      {
        id: "equation-of-vibrating-string",
        name: "Equation of a vibrating string (Wave Equation) and its solutions",
        estimatedMinutes: 180,
        difficulty: 4,
      },
      {
        id: "heat-equation",
        name: "Heat equation and its solutions",
        estimatedMinutes: 150,
        difficulty: 4,
      },
      {
        id: "laplace-equation",
        name: "Laplace equation and its solutions",
        estimatedMinutes: 150,
        difficulty: 4,
      },
    ],
  },

  {
    id: "numerical-analysis-and-computer-programming",
    name: "Numerical Analysis and Computer Programming",
    subtopics: [
      {
        id: "bisection-method",
        name: "Solution of equations: Bisection Method",
        estimatedMinutes: 45,
        difficulty: 1,
      },
      {
        id: "regula-falsi-method",
        name: "Solution of equations: Regula-Falsi Method",
        estimatedMinutes: 60,
        difficulty: 2,
      },
      {
        id: "newton-raphson-method",
        name: "Solution of equations: Newton-Raphson Method (and convergence)",
        estimatedMinutes: 60,
        difficulty: 3,
      },
      {
        id: "gaussian-elimination-jordan",
        name: "System of linear equations: Gaussian elimination and Gauss-Jordan (direct)",
        estimatedMinutes: 60,
        difficulty: 3,
      },
      {
        id: "gauss-seidel",
        name: "System of linear equations: Gauss-Seidel (iterative) method",
        estimatedMinutes: 60,
        difficulty: 3,
      },
      {
        id: "newtons-interpolation",
        name: "Newtons (forward and backward) interpolation",
        estimatedMinutes: 90,
        difficulty: 2,
      },
      {
        id: "lagranges-interpolation",
        name: "Lagranges interpolation",
        estimatedMinutes: 90,
        difficulty: 3,
      },
      {
        id: "trapezoidal-simpsons-rules",
        name: "Numerical integration: Trapezoidal rule, Simpsons (1/3 & 3/8) rules",
        estimatedMinutes: 60,
        difficulty: 2,
      },
      {
        id: "gaussian-quadrature",
        name: "Numerical integration: Gaussian quadrature formula",
        estimatedMinutes: 90,
        difficulty: 4,
      },
      {
        id: "euler-methods",
        name: "Numerical solution of ODEs: Euler and Modified Euler methods",
        estimatedMinutes: 90,
        difficulty: 2,
      },
      {
        id: "runge-kutta-methods",
        name: "Numerical solution of ODEs: Runge Kutta-methods (4th order)",
        estimatedMinutes: 90,
        difficulty: 3,
      },
      {
        id: "number-systems",
        name: "Binary, Octal, Hexadecimal systems, Conversions & Algebra",
        estimatedMinutes: 60,
        difficulty: 2,
      },
      {
        id: "elements-of-computer-systems",
        name: "Elements of computer systems and concept of memory",
        estimatedMinutes: 45,
        difficulty: 1,
      },
      {
        id: "logic-gates-boolean-algebra",
        name: "Basic logic gates and truth tables, Boolean algebra, normal forms",
        estimatedMinutes: 90,
        difficulty: 3,
      },
      {
        id: "data-representation",
        name: "Representation of unsigned/signed integers, reals, double precision & long integers",
        estimatedMinutes: 90,
        difficulty: 4,
      },
      {
        id: "algorithms-and-flowcharts",
        name: "Algorithms and flow charts for solving numerical analysis problems",
        estimatedMinutes: 90,
        difficulty: 4,
      },
    ],
  },

  {
    id: "mechanics-and-fluid-dynamics",
    name: "Mechanics and Fluid Dynamics",
    subtopics: [
      {
        id: "dalemberts-lagranges-equations",
        name: "Generalised coordinates, DAlemberts principle and Lagranges equations",
        estimatedMinutes: 180,
        difficulty: 4,
      },
      {
        id: "hamiltons-equations",
        name: "Hamilton equations (Derivation and Applications)",
        estimatedMinutes: 150,
        difficulty: 4,
      },
      {
        id: "moment-of-inertia",
        name: "Moment of inertia (Inertia tensor, principal axes)",
        estimatedMinutes: 120,
        difficulty: 3,
      },
      {
        id: "rigid-body-motion-2d",
        name: "Motion of rigid bodies in two dimensions",
        estimatedMinutes: 150,
        difficulty: 4,
      },
      {
        id: "continuity-streamlines",
        name: "Equation of continuity; Stream-lines, path of a particle",
        estimatedMinutes: 120,
        difficulty: 3,
      },
      {
        id: "eulers-equation-inviscid",
        name: "Eulers equation of motion for inviscid flow (and Bernoulli's)",
        estimatedMinutes: 120,
        difficulty: 3,
      },
      {
        id: "potential-flow-axisymmetric",
        name: "Potential flow; Two-dimensional and axisymmetric motion",
        estimatedMinutes: 150,
        difficulty: 4,
      },
      {
        id: "sources-sinks-vortex",
        name: "Sources and sinks, vortex motion (Image systems, Milne-Thomson)",
        estimatedMinutes: 180,
        difficulty: 5,
      },
      {
        id: "navier-stokes",
        name: "Navier-Stokes equation for a viscous fluid (and exact solutions)",
        estimatedMinutes: 120,
        difficulty: 4,
      },
    ],
  },


    ],
  },
];

export default optionalSyllabus;